Actualización del Readme
udesa-ai/balancio-kit pull request #11
Opened 2022-05-31 20:19 UTC by AaronLoz

Se agregaron tres versiones del balancio 
plano electrico 
y mejoras visuales

2022-06-02 18:42 UTC, AgustinGrillo requested changes
- Las imagenes "Plano 1.png" y "plano electrico balancio.png" estan repetidas. Tienen que estar solo adentro de la carpeta "resources". Revisar y ordenar tanto la ubicacion, como nombre y cantidad de imagenes.
- Eliminar espacios en los nombres de las mencionadas imagenes. Poner guion bajo en lugar de espacio.
- Revisar ortografia en general.
- En el plano electrico:
   - El conexionado de los motores esta al rves. 
   - En el puente H, las conexiones 'out3' y 'out4' estan invertidas.
   - Revisar el conexionado de las baterias. Respetar color con polaridad.
   - Revisar conexionado de protector de baterias.
   - Conexionado de MCU con IMU y punteh esta OK.

2022-06-02 18:42 UTC, AgustinGrillo commented on README.md
>  <p align="center">
Tratar de que las imagenes queden del mismo tamano y misma relaciond e aspecto.

2022-06-02 18:42 UTC, AgustinGrillo commented on README.md
> +| V 0.7 (Recomendado)  | :star: :star: :star:  | :star: :star: :star:  |      SI      |
Agregar link a archivos de piezas 3d.

2022-06-02 18:42 UTC, AgustinGrillo commented on README.md
> +Fusión
No queda claro que es esto.

2022-06-02 18:42 UTC, AgustinGrillo commented on README.md
> +<summary>Instalación IDE</summary>
```suggestion
<summary>Instalación de la IDE</summary> 
```

2022-06-02 18:42 UTC, AgustinGrillo commented on README.md
> +<summary>Habilitación Microcrontolador</summary>
```suggestion
<summary>Configuración del Microcrontolador</summary> 
```

2022-06-02 18:42 UTC, AgustinGrillo commented on README.md
> +<summary>Compensación IMU</summary>
```suggestion
<summary>Calibración del IMU</summary>
```

2022-06-02 18:42 UTC, AgustinGrillo commented on README.md
> +<summary>Usos</summary>
Sacaria esto

2022-06-02 18:43 UTC, AgustinGrillo commented on README.md
>  [link](https://www.arduino.cc/en/software).
El link:
            [link](https://www.arduino.cc/en/software)

2022-06-02 21:47 UTC, Gabo-Tor commented on README.md
> +| V 0.7 (Recomendado)  | :star: :star: :star:  | :star: :star: :star:  |      SI      |
Hay una lista con los archivos 3d, veria como hacer para no tener los links duplicados, pero si, podriamos linkeara de acá a esa lista, y cuando subamos los .stl agragamos los links en esa lista

2022-06-02 21:48 UTC, Gabo-Tor commented on README.md
> +| V 0.7 (Recomendado)  | :star: :star: :star:  | :star: :star: :star:  |      SI      |
Agregar pequeñas imagenes de cada modelo en la tabla

2022-06-07 19:14 UTC, Gabo-Tor requested changes
Ahí te tiré alguno comments más para ver el martes

2022-06-07 19:14 UTC, Gabo-Tor commented on README.md
> +|                      |      Estabilidad      |  Facilidad de Armado  | Requiere I3D | Plano de Impresión 3D|Foto de la versión|
```suggestion
|                      |      Estabilidad      |  Facilidad de Armado  | Requiere I3D | Plano de Impresión 3D|Foto|
```

2022-06-07 19:14 UTC, Gabo-Tor commented on README.md
> +    <img src="resources/Balancio_plano.png" width="650">
- Las baterías están al revés el lado positivo sale para el cable rojo (bien) pero eso va a B- y el cable negro va a B+.
- Está mal el cable negro del motor izquierdo que se cruza con el negativo, debería tener un salto para mostrar que no va conectado
- El cable magenta tiene una curva innecesaria :/
- Los cables conectados a BM hagamoslos full negro

2022-06-07 19:14 UTC, Gabo-Tor commented on README.md
> +    La aplicación está creada en [MIT App Inventor](https://appinventor.mit.edu/).
```suggestion
La aplicación está creada en [MIT App Inventor](https://appinventor.mit.edu/).
```

2022-06-07 19:14 UTC, Gabo-Tor commented on README.md
> +    La aplicación está creada en [MIT App Inventor](https://appinventor.mit.edu/).
Está roto el link?

2022-06-07 19:14 UTC, Gabo-Tor commented on README.md
>  [link](https://www.arduino.cc/en/software).
Es porque eso es sintaxis markdown y está dentro de sintaxis HTML, arreglar esto

> Se rompio esto (?)

2022-06-10 15:14 UTC, Gabo-Tor commented on README.md
>  ## Ensamblaje :wrench:
Falta la BMS acá

2022-06-10 18:51 UTC, Tadeo-Casiraghi requested changes
Agregue las inercias y las masas. Agregue los tiempos de impresión de las piezas. Corregí un pequeño error

2022-06-10 18:51 UTC, Tadeo-Casiraghi commented on README.md
> +|         V 0.5        |         :star:        | :star: :star: :star:  |      SI      |                      |<img src="resources/balanciov3.jpg" width="60">|
```suggestion
| V 0.7 (Recomendado)  | :star: :star: :star:  | :star: :star: :star:  |      SI (Base_Baterias:47m Cuerpo:2h36m)      |                      |<img src="resources/Balancio_0.71.jpg" width="70">|
|   V 0.6 AKA:Wall-e   | :star: :star: :star:  |         :star:        |      SI  (Cuerpo_Inferior:5h25m Cuerpo_Superior:5h11m Placa_inferior:58m Placa_superior:55m Cabeza:3h19m)    |                      |<img src="resources/Balancio_0.5.jpg" width="60">|
|         V 0.5        |         :star:        | :star: :star: :star:  |      SI (Aro:49m Cuerpo:4h42m)     |                      |<img src="resources/balanciov3.jpg" width="60">|
```

2022-06-10 18:51 UTC, Tadeo-Casiraghi commented on README.md
>  - Wheel spins on sturtup
```suggestion
- Wheel spins on startup
```

2022-06-10 18:51 UTC, Tadeo-Casiraghi commented on README.md
> +### Aplicación
```suggestion
### Variables Físicas de la versión 7

# Cuerpo
Masa sin ruedas: 0.244 kg
Posición del centro de masa con respecto al eje de los motores y el centro simétrico del cuerpo: x = 1.55 mm
                                                                                                                                                           y ~= 0 mm
                                                                                                                                                           z = 31 mm
Inercia sin ruedas desde el centro de masa (kg.m2):  Ixx = 0.0006945
                                                                                    Ixy ~= 0
                                                                                    Iyy = 0.0006536
                                                                                    Ixz = -0.000013447 
                                                                                    Iyz ~= 0
                                                                                    Izz = 0.0001937

# Rueda
Masa de una rueda: 0.029 kg
Posición del centro de masa con respecto al eje de los motores y el borde del agarre:  x = 0 mm 
                                                                                                                                          y = 15.6 mm
                                                                                                                                          z = 0 mm
Inercia de la rueda desde el centro de masa (kg.m2):  Ixx = 0.000011729
                                                                                      Ixy ~= 0
                                                                                      Iyy = 0.000021531
                                                                                      Ixz ~= 0
                                                                                      Iyz ~= 0
                                                                                      Izz = 0.000011729

### Aplicación 
```

2022-06-15 17:03 UTC, merged